image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: edsonmichaque/tyk-sync-foobar

services:
  - docker:dind

stages:
  - release

before_script:
  - apk add --no-cache make
  - echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin

release:
  stage: release
  script:
    - make build VERSION=${CI_COMMIT_TAG} IMAGE_NAME=${IMAGE_NAME}
    - apk add --no-cache curl
    - curl -L "https://gitlab.com/gitlab-org/release-cli/-/releases/v0.16.0/downloads/release-cli-linux-amd64" -o /usr/local/bin/release-cli
    - chmod +x /usr/local/bin/release-cli
    - make release-gitlab VERSION=${CI_COMMIT_TAG} IMAGE_NAME=${IMAGE_NAME}
    - make docker VERSION=${CI_COMMIT_TAG} IMAGE_NAME=${IMAGE_NAME}
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG