name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on new tags that start with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build distributions
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        make all VERSION=$VERSION

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        gh release create $VERSION dist/* --title "Release $VERSION" --notes "Automated release of version $VERSION"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        make docker-publish VERSION=$VERSION